title: TabFloater - Picture-in-Picture for any tab
googleAnalyticsId: UA-175107528-3
url: "https://www.tabfloater.io"
repository: tabfloater/tabfloater.github.io
plugins:
  - jekyll-sitemap
exclude:
  - CNAME
  - Gemfile*
  - LICENSE
  - README.md
  - serve.sh
